import sys,re
p="/home/claude/manuscript_v5.md"; s=open(p).read()
def rep(old,new):
    global s
    if s.count(old)!=1: print("!! count",s.count(old),old[:80]); sys.exit(1)
    s=s.replace(old,new)
rep('date: "Draft v4 — September 2026 (JEBO version)"','date: "Draft v5 — September 2026 (JEBO version)"')
# Intro para 2: magnitudes on both results
rep("Those borrowers default less — 13.3 percent against 20.0 percent in the raw data, and roughly 30 percent less after I condition on grade, FICO, income, debt-to-income, loan terms, state and year. The two facts sit uneasily together. Borrowers who talk about faith in their loan request are, if anything, worse credit risks than their scores suggest; borrowers whose working lives are embedded in a religious institution are better ones.",
    "Those borrowers default less: 13.3 percent against 20.0 percent in the raw data, and about five percentage points less after I condition on grade, FICO, income, debt-to-income, loan terms, state and year. The two facts sit uneasily together. Borrowers who talk about faith in their loan request default about three percentage points more than their scores predict; borrowers whose working lives are embedded in a religious institution default about five points less.")
# Literature paragraph: split into two, add explicit contribution paragraph
rep(" The third literature is the work on borrower-supplied information in online credit markets,",
    "\n\nThe third literature is the work on borrower-supplied information in online credit markets,")
rep("since descriptions that report religious *practice* rather than merely invoking faith behave like the affiliation signal.",
    "since descriptions that report religious *practice* rather than merely invoking faith behave like the affiliation signal.\n\nThe paper's contribution is therefore three things the literature did not know. Religion enters an individual credit file in two observable forms that carry opposite information about default, so \"religion\" is not a single credit signal. The protective form is an affiliation with a community, not a vocation or a belief, and its association with default grows with the density of that community. And local religiosity, the variable the finance literature has relied on, does not carry the individual signal and in this market points the other way.")
# 5.1: column references and benchmark
rep("Table 2 reports the affiliation estimates. In the full terminal sample the odds ratio is 0.69 (clustered standard error on the log-odds 0.041; p ≈ 7 × 10⁻¹⁹), an average marginal effect of −4.8 percentage points against a base default rate of 20 percent. The estimate is 0.61 for loans issued in 2008–2014 and 0.74 for 2015–2018;",
    "Table 2 reports the affiliation estimates. Column (1) of Panel A gives the confirmatory specification on the full terminal sample: the odds ratio is 0.69 (clustered standard error on the log-odds 0.041; p ≈ 7 × 10⁻¹⁹), an average marginal effect of −4.8 percentage points against a base default rate of 20 percent, or about a quarter of the base rate. Columns (2) and (3) split the sample by period: the estimate is 0.61 for loans issued in 2008–2014 and 0.74 for 2015–2018;")
# 5.2: column references
rep("Table 3 builds the narrative estimate one control set at a time. With credit and loan controls only, religious language carries an odds ratio of 1.27 (p = 0.018). Adding log length raises it to 1.34 — long descriptions default less, and religious descriptions are long — and adding the six text dictionaries brings it back to 1.28 (p = 0.016; +3.2 points). Replacing log length with length deciles changes nothing.",
    "Table 3 builds the narrative estimate one control set at a time. With credit and loan controls only (column 1), religious language carries an odds ratio of 1.27 (p = 0.018). Adding log length (column 2) moves it to 1.34, because long descriptions default less and religious descriptions are long; adding the six text dictionaries (column 3, the pre-specified specification) brings it back to 1.28 (p = 0.016), an average marginal effect of +3.2 percentage points against a base rate of 15 percent in the description sample. Replacing log length with length deciles (column 4) changes nothing.")
# 5.4: causal verb on own control estimate; null result phrasing
rep("Local unemployment matters for default in the expected way — a standard deviation higher rate at origination raises the odds by 9.5 percent, a standard deviation larger rise over the loan's life by 3.2 percent — but the affiliation advantage does not widen when unemployment rises (interaction 0.98, p = 0.69) or when it is high (0.95, p = 0.38), and it is not monotone across shock terciles (0.58, 0.74, 0.70).",
    "Local unemployment is associated with default in the expected direction — a standard deviation higher rate at origination with 9.5 percent higher odds, a standard deviation larger rise over the loan's life with 3.2 percent higher odds — but the affiliation advantage does not widen when unemployment rises (interaction odds ratio 0.98, p = 0.69, indistinguishable from one) or when it is high (0.95, p = 0.38), and it is not monotone across shock terciles (0.58, 0.74, 0.70).")
open(p,"w").write(s); print("ok")
