import re, sys
p="/home/claude/manuscript_v2.md"; s=open(p).read()
def rep(old,new,count=1):
    global s
    n=s.count(old)
    if n!=count: print("!! count",n,"for:",old[:70]); sys.exit(1)
    s=s.replace(old,new)
rep('date: "Draft v1 — September 2026 (JEBO version)"','date: "Draft v2 — September 2026 (JEBO version)"')
# Abstract
rep("The estimate survives controls for eight other stable occupations, entropy balancing on 76 covariate moments, double machine learning, sensitivity analysis for unobserved confounding, and replication on Prosper.",
    "The estimate survives controls for eight other stable occupations, comparison with and exact matching to nonprofit, education and healthcare workers — who show no such advantage — entropy balancing on 76 covariate moments, double machine learning, sensitivity analysis for unobserved confounding, and replication on Prosper.")
rep("and with religious language acting as cheap talk.","and with religious language as a low-cost, unverifiable signal whose information runs against the sender's intent.")
# Intro para
rep("behaves like cheap talk in the signaling sense: it costs nothing to write, it travels with hardship, gratitude and appeals for help, and its association with default is consistent in sign but not strong.",
    "behaves like a low-cost signal: it costs nothing to write, cannot be verified, travels with hardship, gratitude and appeals for help, and its association with default is consistent in sign but not strong.")
# Literature paragraph (replace whole)
i=s.index("The finding speaks to three literatures."); j=s.index("\n",i)
new_lit=("The finding speaks to three literatures, and I should be precise about what each already knows. The first is the work on religion, social capital and economic behavior. Religious belief is associated with trust, reciprocity and cooperative attitudes in survey data across countries (Guiso, Sapienza and Zingales, 2003; Valencia Caicedo, Dohmen and Pondorfer, 2023), the density of congregations predicts local social capital and business activity (Deller, Conroy and Markeson, 2018), and historical religious activity leaves a long trace in it (Deng, Liu and Yan, 2025). That literature establishes that religion builds the kind of network group-lending theory needs; it does not observe an individual's place in such a network alongside a financial obligation with money at stake. The second is the finance literature on religion and credit, which has identified religion mostly through the lending contract or the borrower's surroundings. Islamic loans default less than conventional loans to comparable borrowers (Baele, Farooq and Ongena, 2014); firms in more religious U.S. counties borrow at lower spreads with fewer covenants (He and Hu, 2016; Chen, Huang, Lobo and Wang, 2016); credit unions in more religious counties lend more cheaply and hold better loans (Davidson, Ngo and Wang, 2026); county adherence predicts lower mortgage delinquency and less misrepresentation (Li and Ucar, 2022; Conklin, Diop and Qiu, 2022). At the individual level, religious affiliation is associated with the kinds of debt a household carries (Clifton, Brewer and Upenieks, 2023) and religiosity in adolescence with less financial distress in adulthood (Lei, Lu, Niu and Zhou, 2024), but neither study observes a loan and its repayment. What this paper adds is not that religion matters for credit, which is established, but that religion enters an individual credit file in two observable forms — an institutional affiliation and a self-authored text — that carry opposite information about the repayment of the same kind of loan in the same market; and that the informative one is not the regional signal seen from closer up. Local religiosity does not protect borrowers here, while individual affiliation does, and the individual effect is amplified rather than explained by the local one. The third literature is the work on borrower text in credit markets (Netzer et al., 2019; Nowak, Ross and Yencha, 2018; Sanz-Guerrero and Arroyo, 2025), which has established that words predict default — Netzer et al. list mentions of God among them — and has been less interested in which words carry information of their own rather than proxying for circumstance. Religious language, it turns out, mostly proxies; the part that does not is the part one would predict from theory, since descriptions that report religious *practice* rather than merely invoking faith behave like the affiliation signal.")
s=s[:i]+new_lit+s[j:]
# 2.1
rep("Iannaccone (1992) argued that the demands religious groups place on members, which look wasteful from outside, are what make the group's cooperation sustainable: they screen out free riders and raise the cost of exit.",
    "Iannaccone (1992) argued that the demands religious groups place on members, which look wasteful from outside, are what make the group's cooperation sustainable: they screen out free riders and raise the cost of exit; strict churches are strong for the same reason, because their demands select for committed members and make each member's participation visible to the rest (Iannaccone, 1994).")
rep("Religious attitudes toward cooperation and thrift show up in survey data across countries (Guiso, Sapienza and Zingales, 2003).",
    "Religious attitudes toward cooperation and thrift show up in survey data across countries (Guiso, Sapienza and Zingales, 2003), and believers report more positive reciprocity, altruism and trust on experimentally validated preference measures (Valencia Caicedo, Dohmen and Pondorfer, 2023).")
rep("denser networks of congregations mean more overlapping ties, more people who would hear of a default, and a higher cost of one.",
    "denser networks of congregations mean more overlapping ties, more people who would hear of a default, and a higher cost of one. The argument extends the logic of social collateral from groups a lender organizes to an affiliation a borrower reports; it does not introduce a new mechanism, and I do not observe the community's monitoring directly. What I can observe is whether the pattern of default matches what that logic predicts and fails to match what its rivals predict.")
# 2.2
rep("## 2.2 Language as cheap talk","## 2.2 Language as a low-cost signal")
rep("a message anyone can send at no cost, to an audience that would like to hear it, is cheap talk, and a rational receiver discounts it (Spence, 1973; Crawford and Sobel, 1982; Farrell and Rabin, 1996).",
    "a message anyone can send at no cost, to an audience that would like to hear it, is cheap talk in the technical sense, and whether it carries information depends on who chooses to send it rather than on what it says (Spence, 1973; Crawford and Sobel, 1982; Farrell and Rabin, 1996).")
rep("That residual is what the cheap-talk reading predicts should remain","That residual is what the low-cost-signal reading predicts should remain")
# Section 4
rep("this rules out a generic public-or-institutional-employment effect but not a feature peculiar to church employment.",
    "this rules out a generic public-or-institutional-employment effect but not a feature peculiar to church employment. Against the sharper version of that objection — that church employees resemble other mission-driven, modestly paid service workers rather than the average borrower — I compare them with borrowers whose job titles place them in nonprofit and social-service work, education, or healthcare, first with those occupations as the only comparison group and then within coarsened-exact-matching cells, and I ask whether those occupations show a default advantage of their own.")
# 5.1 add Panel B paragraph
rep("Prosper replicates it (Table 8).",
    "Panel B of Table 2 takes the objection one step further. If the affiliation effect were a property of mission-driven, modestly paid service work, borrowers in the occupations nearest to church employment should show it too, and comparing affiliated borrowers with those occupations alone should shrink it. Neither happens. Social workers, case managers and counselors (11,592 loans) default no less than other borrowers (odds ratio 1.02), and neither do healthcare workers (1.02, on 76,981 loans); teachers and other education workers default modestly less (0.94). With each of these groups as the only comparison, the affiliation odds ratio is 0.69, 0.68 and 0.75 respectively, and 0.71 against all three together. Matching affiliated borrowers exactly to those neighbors on grade, year, a 20-point FICO band, income quartile, employment length, homeownership and term (2,766 matched affiliated loans in 2,234 cells) gives 0.70; a similar match to the eight stable occupations on income decile, employment length, grade, year and term gives 0.74 (3,008 matched). Whatever the affiliation captures, it is not shared by the occupations that most resemble it in pay, tenure or purpose.\n\nProsper replicates it (Table 8).")
# 5.2 add power / repeated cross-fitting / gradient
rep("Table 4 puts both indicators in the same regression.",
    "Two further checks put the imprecision in its place. First, the estimate does not depend on the sample split: repeating the cross-fitting twenty times gives a median of +3.2 points (p = 0.031) with the dictionary controls, significant at 5 percent in all twenty splits, and +3.0 (p = 0.045) with the TF-IDF representation, significant in twelve of twenty__REPFILL__. Second, the imprecision is what the sample size implies. With 681 treated loans and a base rate of 15 percent, the smallest effect a one-sided 5-percent test detects with 80 percent power is 3.4 points; the power to detect the +2.3 to +3.1 points estimated in the text-conditioned specifications is between 50 and 72 percent. A more precise estimate would require more religious descriptions than exist — the classifier screen of Appendix B found a few dozen outside the dictionary, not thousands. What the data can add is a gradient. Replacing the indicator with the number of religious terms in the description, the odds ratio is 1.14 for one term (p = 0.24), 1.56 for two (p = 0.06) and 1.87 for three or more (p = 0.07); within the 681 flagged descriptions more terms mean more default (p = 0.11); and the continuous log-count specification gives 1.37 (p = 0.006). None of this was pre-specified, and I report it as a pattern consistent with the direction of H2 rather than as a test.\n\nTable 4 puts both indicators in the same regression.")
# 5.3 hierarchy
rep("Whatever protects the church secretary is not the general stability of institutional employment.",
    "Whatever protects the church secretary is not the general stability of institutional employment.\n\nA last, exploratory split points the same way. Among clergy, senior, lead and executive pastors (497 loans) have an odds ratio of 0.45 (p < 0.001; raw default 8.7 percent), associate, youth and assistant pastors (253 loans) 0.70 (p = 0.08), and the remaining affiliated borrowers 0.74. Standing within the community and the cost of losing it move together — but so do seniority and income, and I cannot separate the two, so this is a pattern rather than a test.")
# 5.5 replace paragraph
i=s.index("The religiosity literature in finance is almost entirely about places"); j=s.index("\n",i)
new55=("The religiosity literature in finance is almost entirely about places, and it is worth asking whether my signals are the same thing seen from closer up. They are not. In that literature a more religious surrounding is a favorable one: firms in more religious counties borrow at lower spreads with fewer covenants (He and Hu, 2016; Chen et al., 2016), credit unions there lend more cheaply and hold better loans (Davidson, Ngo and Wang, 2026), and county adherence predicts lower mortgage delinquency (Li and Ucar, 2022). In this market local religiosity does nothing of the kind. Within state, borrowers from more religious ZIP3 areas default slightly *more* (odds ratio 1.04 per standard deviation of adherence, 1.06 per standard deviation of congregation density; Table 6), and the evangelical share is unrelated to default. I do not have an explanation and offer none. The populations differ — those studies concern firms, institutions or mortgages, and mine concerns individuals who sought unsecured credit online — and the within-state residual variation in religiosity is correlated with income and urbanicity in ways that state fixed effects and my income control may not fully absorb. I flag it as a contrast with the county literature rather than a contradiction of it. What the contrast makes clear is that whatever protects the affiliated borrower is not a property of religious places. It is a property of belonging to a religious institution, and it is amplified by the density of such institutions rather than replaced by it: the affiliation odds ratio is 0.71 in the least religious tercile of areas, 0.83 in the middle and 0.58 in the most religious (Appendix Table A2). A religious environment, on this evidence, is not itself a borrower-level credit signal; the value of an individual's affiliation depends on the community around it.")
s=s[:i]+new55+s[j:]
# 6.4 replace first paragraph
i=s.index("This is an observational study of one platform's borrowers"); j=s.index("\n",i)
new64=("This is an observational study of one platform's borrowers, most of whom are American and, where religion is visible, Christian. There is no instrument for working in a church and no natural experiment that moves people into or out of one, and the public file has no borrower identifier, so a within-borrower design that follows the same person across an occupational change is not available; the member identifier is empty for every loan. The platform also does not record age, education, marital status or household structure, on any of which church employees may differ from other borrowers. The affiliation indicator comes from a free-text job title and certainly misses affiliated borrowers who described their job differently; that biases the estimate toward zero, not away from it. The description sample ends in 2014 because the platform stopped collecting descriptions, and religious language is rare enough that the narrative estimate is imprecise in the strictest specifications. The evidence on mechanism is consistent with a community-based account and difficult to reconcile with the observable labor-market explanations I can test — pay, tenure, the generic stability of institutional jobs, and the occupations nearest to church work — but it does not identify the mechanism causally, and the labor-market test has too little adverse variation in these years to settle the income-stability question. What the paper establishes is narrower than a mechanism: that two observable traces of religion carry opposite credit information, that the protective one belongs to the community rather than the vocation and grows with the community's density, and that the market did not price either.")
s=s[:i]+new64+s[j:]
# Conclusion
rep("and religious language as cheap talk. For lenders","and religious language as a low-cost signal that is informative in spite of, not because of, what it says. For lenders")
# Figure 1 after the 'This paper is about that contrast' paragraph
rep("The finding speaks to three literatures, and I should be precise",
    "![Figure 1. Two channels through which religion enters a consumer-credit file. Left: institutional affiliation revealed by the job title; right: religious language volunteered in the loan description. Odds ratios from Tables 2 and 3.](fig1_channels.png)\n\nThe finding speaks to three literatures, and I should be precise")
# References
refs={
"Baele, L., Farooq, M., & Ongena, S. (2014). Of religion and redemption: Evidence from default on Islamic loans. *Journal of Banking & Finance*, 44, 141–159.":"Anglin",
"Chen, H., Huang, H. H., Lobo, G. J., & Wang, C. (2016). Religiosity and the cost of debt. *Journal of Banking & Finance*, 70, 70–85.":"Chernozhukov",
"Clifton, T., Brewer, M., & Upenieks, L. (2023). Religious affiliation and debt among U.S. households. *Social Science Research*, 115, 102911.":"Conklin",
"Davidson, T., Ngo, T., & Wang, H. (2026). Credit union member benefits: Does local religiosity matter? *Journal of Financial Services Research*, 69(3), 181–217.":"Farrell",
"Deller, S. C., Conroy, T., & Markeson, B. (2018). Social capital, religion and small business activity. *Journal of Economic Behavior & Organization*, 155, 365–381.":"Farrell",
"Deng, J., Liu, Q., & Yan, S. (2025). Fostering social capital: The long-term effects of Protestant activities on corporate tax avoidance in modern China. *Journal of Economic Behavior & Organization*, 234, 107014.":"Farrell",
"He, W., & Hu, M. R. (2016). Religion and bank loan terms. *Journal of Banking & Finance*, 64, 205–215.":"Iannaccone, L. R. (1992)",
"Iannaccone, L. R. (1994). Why strict churches are strong. *American Journal of Sociology*, 99(5), 1180–1211.":"Karlan",
"Lei, L., Lu, W., Niu, G., & Zhou, Y. (2024). Religiosity and financial distress of the young. *Journal of Banking & Finance*, 168, 107276.":"Li, L.",
"Valencia Caicedo, F., Dohmen, T., & Pondorfer, A. (2023). Religion and cooperation across the globe. *Journal of Economic Behavior & Organization*, 215, 479–489.":None,
}
for ref,before in refs.items():
    if before is None: s=s.rstrip()+"\n\n"+ref+"\n"
    else:
        k=s.index("\n"+before); s=s[:k]+"\n"+ref+"\n"+s[k:]
rep("Nowak, A., Ross, A., & Yencha, C. (2018). Small business borrowing and peer-to-peer lending: Evidence from Lending Club. *Contemporary Economic Policy*, 36(2), 318–336. [서지 미확인 — 확인 필요]",
    "Nowak, A., Ross, A., & Yencha, C. (2018). Small business borrowing and peer-to-peer lending: Evidence from Lending Club. *Contemporary Economic Policy*, 36(2), 318–336.")
rep("Sanz-Guerrero, M., & Arroyo, J. (2024). Credit risk meets large language models: Building a risk indicator from loan descriptions in P2P lending. [서지 미확인 — 확인 필요]",
    "Sanz-Guerrero, M., & Arroyo, J. (2025). Credit risk meets large language models: Building a risk indicator from loan descriptions in P2P lending. *Inteligencia Artificial*, 28(75), 220–247.")
open(p,"w").write(s); print("ok", len(s.split()))
