import sys
p="/home/claude/manuscript_v6.md"; s=open("/home/claude/manuscript_v5.md").read()
def rep(old,new):
    global s
    if s.count(old)!=1: print("!! count",s.count(old),old[:80]); sys.exit(1)
    s=s.replace(old,new)
rep('date: "Draft v5 — September 2026 (JEBO version)"','date: "Draft v6 — September 2026 (JEBO version)"')
# 3.2 affiliation audit + civil parish
rep("The distinction between role and staff is the basis of the within-institution comparison in Section 5.3.",
    "The distinction between role and staff is the basis of the within-institution comparison in Section 5.3. To check the indicator's precision I had 200 randomly drawn affiliated job titles coded by a reader (Appendix Table B2): 146 are clerical roles, 48 are non-clerical church staff, 2 are not religious employment at all, and 4 cannot be classified from the title. The two clear errors share a cause — in Louisiana a \"parish\" is a county, so \"Ouachita Parish Sheriff's Office\" matches the organization word — and a targeted rule identifies 30 such civil-parish titles in the terminal sample. Dropping them moves the affiliation odds ratio from 0.692 to 0.683, and I keep them in the main sample so that the reported estimate is the one the pre-specified rule produces.")
# 3.1 selection into description sample
rep("The description subsample has 123,292 loans (15.3 percent defaulted); it is an earlier and somewhat riskier slice of the platform's history, which is why every specification carries origination-year fixed effects.",
    "The description subsample has 123,292 loans (15.3 percent defaulted); it is an earlier and somewhat riskier slice of the platform's history, which is why every specification carries origination-year fixed effects. Writing a description was a choice, and Appendix Table C2 reports what predicts it among 2008–2014 loans: the year of origination above all, then grade and loan size, while religious-institution affiliation has no relation to it (odds ratio 1.02, p = 0.81). The narrative results therefore describe borrowers who chose to write, and I do not extrapolate them to those who did not.")
# 4: alternative SE
rep("H2 is estimated on the full description sample with the six text dictionaries and log length added.",
    "H2 is estimated on the full description sample with the six text dictionaries and log length added. Clustering by three-digit ZIP area or by month of origination instead of by state changes the standard errors but not the conclusions (Appendix Table C3), and Appendix Table C1 shows the covariate balance that entropy balancing achieves.")
# 5.1 Figure 2 after Panel B paragraph
rep("Whatever the affiliation captures, it is not shared by the occupations that most resemble it in pay, tenure or purpose.",
    "Whatever the affiliation captures, it is not shared by the occupations that most resemble it in pay, tenure or purpose. Figure 2 collects the affiliation estimates from Table 2, the neighbor-occupation comparisons and the Prosper replication in one plot; every interval lies below one and the point estimates span 0.61 to 0.75.\n\n![Figure 2. Religious-institution affiliation and default across specifications. Odds ratios with 95% confidence intervals (log scale) from Table 2, Panels A and B, and Table 8. Intervals for estimates reported with p-values only are recovered from the p-value.](fig2_forest.png)")
# 5.2 Figure 5 after DML paragraph (before "Two further checks")
rep("Two further checks put the imprecision in its place.",
    "Figure 5 plots the nine double machine learning estimates with their intervals: the point estimates move within a narrow band, and what separates the specifications is only whether the lower bound clears zero.\n\n![Figure 5. Religious language and default: double machine learning estimates by text representation. Partially linear DoubleML with CatBoost nuisance functions, 5-fold cross-fitting; \"20 splits\" aggregates twenty repeated sample splits by the median. Bars are 95% confidence intervals.](fig5_dml.png)\n\nTwo further checks put the imprecision in its place.")
# 5.4 Figure 3 after Table 6 paragraph
rep("which is what one expects of a message whose meaning does not depend on who is listening.",
    "which is what one expects of a message whose meaning does not depend on who is listening. Figure 3 shows the two patterns by quintile. The affiliation odds ratio is 0.85 in the two least dense quintiles of ZIP areas and 0.62 to 0.68 in the three densest, a step rather than a smooth gradient; the religious-language odds ratio moves between 1.10 and 1.50 across adherence quintiles with no ordering, and only the top quintile's interval excludes one.\n\n![Figure 3. Heterogeneity by local religiosity. Panel A: affiliation odds ratio by quintile of congregation density in the borrower's ZIP3 area, from one logit with affiliation interacted with quintile indicators, full controls and state fixed effects. Panel B: religious-language odds ratio by quintile of the adherence rate, description-sample specification of Table 3, column 3. Bars are 95% confidence intervals; n is the number of treated loans in the quintile.](fig3_density.png)")
# 5.6 Figure 4
rep("I treat this as suggestive: the default date is approximate and the comparison groups are subsampled.",
    "I treat this as suggestive: the default date is approximate and the comparison groups are subsampled. Figure 4 shows the same timing without a model. Among 36-month loans, cumulative default of affiliated borrowers runs below that of other borrowers from the first year (2.1 against 3.6 percent at twelve months, 9.5 against 14.1 at maturity), while the curve for religious language tracks the comparison group for the first year (3.0 against 2.8 percent) and separates afterward (17.4 against 12.6 at maturity).\n\n![Figure 4. Cumulative default by months since origination, 36-month loans. Default is dated four months after the last payment. Comparison groups are reweighted to the treated group's grade × origination-year distribution. Panel A: 2,398 affiliated loans in the terminal sample; Panel B: 507 religious-language loans in the description sample.](fig4_cumdefault.png)")
open(p,"w").write(s); print("ok")
