import pandas as pd, numpy as np, warnings; warnings.filterwarnings("ignore")
import statsmodels.formula.api as smf
f="/mnt/user-data/uploads/Lending Club/accepted_2007_to_2018Q4.csv.gz"
cols=['id','recoveries','total_pymnt','total_rec_prncp','funded_amnt','hardship_flag','debt_settlement_flag','last_pymnt_d','issue_d','term','loan_status','int_rate','grade','sub_grade','addr_state']
ex=pd.concat([c for c in pd.read_csv(f, usecols=cols, chunksize=300000, low_memory=False)]); ex['id']=pd.to_numeric(ex.id,errors='coerce'); ex=ex[ex.id.notna()]; ex['id']=ex.id.astype(int)
df=pd.read_pickle("lc_final.pkl"); df['id']=pd.to_numeric(df.id,errors='coerce'); df=df[df.id.notna()]; df['id']=df.id.astype(int)
et=df['emp_title'].fillna('').str.lower().str.strip()
role=et.str.contains(r"\bpastor\b|\bminister\b|\bministry\b|\bclergy\b|\bpriest\b|\bchaplain\b|\brabbi\b|\bmissionar|\breverend\b|\bevangelist\b|\bdeacon\b|\bworship\b|\bimam\b|\bseminar(y|ian)\b", regex=True)
org=et.str.contains(r"\bchurch\b|\bparish\b|\bdiocese\b|\bcongregation\b|\bsynagogue\b|\bmosque\b", regex=True)
inst=et.str.contains(r"hospital|health|medical|charit|university|college|school|academy|insurance|bank|credit union|hospice|clinic|services inc|mutual", regex=True)
df['clergy']=role|(org&~inst)
m=df[['id','clergy','relig_strict','has_desc','grade','year','fico_range_low','annual_inc','dti','loan_amnt','term','int_rate','purpose','addr_state','loan_status','desc_len']].merge(ex[['id','recoveries','total_pymnt','total_rec_prncp','funded_amnt','hardship_flag','debt_settlement_flag','last_pymnt_d','sub_grade','issue_d']],on='id')
m['int']=m.int_rate.astype(str).str.rstrip('%').astype(float); m['linc']=np.log1p(m.annual_inc.fillna(0)); m['lamt']=np.log(m.loan_amnt); m['t60']=m.term.astype(str).str.contains('60').astype(int); m['yr']=m.year.astype('Int64').astype(str)
term=m[m.loan_status.isin(['Fully Paid','Charged Off','Default'])].copy(); term['default']=term.loan_status.isin(['Charged Off','Default']).astype(int)
print("=== 1. 부도 후 회수(willingness to pay after charge-off) ===")
co=term[term.default==1].copy(); co['rec_rate']=co.recoveries/co.funded_amnt
print("charged-off n",len(co),"clergy",co.clergy.sum(),"relig_desc",co.relig_strict[co.has_desc].sum())
print("recovery rate mean: clergy",co[co.clergy].rec_rate.mean().round(4),"other",co[~co.clergy].rec_rate.mean().round(4),"| relig desc",co[co.has_desc&co.relig_strict].rec_rate.mean().round(4),"other desc",co[co.has_desc&~co.relig_strict].rec_rate.mean().round(4))
print("any recovery>0: clergy",(co[co.clergy].recoveries>0).mean().round(3),"other",(co[~co.clergy].recoveries>0).mean().round(3))
r=smf.ols("rec_rate ~ clergy + C(grade)+C(yr)+int+linc+dti+t60+lamt", data=co).fit(); print("OLS rec_rate~clergy coef",r.params['clergy[T.True]'].round(4),"p",r.pvalues['clergy[T.True]'].round(4))
print("\n=== 2. 시장 가격화 여부: 같은 sub_grade 내 금리 차이 ===")
# LC prices by sub_grade x time; check whether clergy/relig get different int within sub_grade-year (should be ~0 if not priced)
p=smf.ols("int ~ clergy + C(sub_grade)+C(yr)+C(t60)", data=m.sample(400000,random_state=0).append(m[m.clergy]) if False else pd.concat([m[m.clergy], m[~m.clergy].sample(300000,random_state=0)])).fit()
print("int ~ clergy | sub_grade,yr,term: coef",p.params['clergy[T.True]'].round(4),"p",p.pvalues['clergy[T.True]'].round(4))
d=m[m.has_desc]; p2=smf.ols("int ~ relig_strict + C(sub_grade)+C(yr)+C(t60)", data=d).fit(); print("int ~ relig_desc | sub_grade,yr,term: coef",p2.params['relig_strict[T.True]'].round(4),"p",p2.pvalues['relig_strict[T.True]'].round(4))
print("\n=== 3. 하드십/채무조정 이용 (2017+ 관측 변수) ===")
for v in ['hardship_flag','debt_settlement_flag']:
    y=(m[v]=='Y').astype(int); print(v,"rate clergy",y[m.clergy].mean().round(4),"other",y[~m.clergy].mean().round(4), "n_clergy",m.clergy.sum())
print("\n=== 4. 조기상환(Fully Paid before term) ===")
fp=term[term.default==0].copy(); fp['months']=(pd.to_datetime(fp.last_pymnt_d,format='%b-%Y',errors='coerce')-pd.to_datetime(fp.issue_d,format='%b-%Y',errors='coerce')).dt.days/30.4; fp['tm']=np.where(fp.t60==1,60,36); fp['early']=(fp.months<fp.tm-6).astype(int)
print("early payoff (>6m before term): clergy",fp[fp.clergy].early.mean().round(3),"other",fp[~fp.clergy].early.mean().round(3),"| relig desc",fp[fp.has_desc&fp.relig_strict].early.mean().round(3),"other desc",fp[fp.has_desc&~fp.relig_strict].early.mean().round(3))
print("\n=== 5. 주(state) 종교성 상호작용: Bible Belt vs 기타 ===")
bible=['AL','AR','GA','KY','LA','MS','NC','OK','SC','TN','TX','WV']
term['bb']=term.addr_state.isin(bible).astype(int)
S=pd.concat([term[term.clergy], term[~term.clergy].sample(250000,random_state=1)])
mi=smf.logit("default ~ clergy*bb + C(grade)+C(yr)+int+linc+dti+t60+lamt", data=S).fit(disp=0,maxiter=200)
print("clergy OR",np.exp(mi.params['clergy[T.True]']).round(3),"p",mi.pvalues['clergy[T.True]'].round(4),"| clergy x BibleBelt OR",np.exp(mi.params['clergy[T.True]:bb']).round(3),"p",mi.pvalues['clergy[T.True]:bb'].round(4))
print("clergy share BibleBelt",term[term.clergy].bb.mean().round(3),"vs all",term.bb.mean().round(3))
dd=term[term.has_desc]; mj=smf.logit("default ~ relig_strict*bb + C(grade)+C(yr)+int+linc+dti+t60+lamt+np.log1p(desc_len)", data=dd).fit(disp=0,maxiter=200)
print("relig_desc OR",np.exp(mj.params['relig_strict[T.True]']).round(3),"p",mj.pvalues['relig_strict[T.True]'].round(4),"| x BibleBelt OR",np.exp(mj.params['relig_strict[T.True]:bb']).round(3),"p",mj.pvalues['relig_strict[T.True]:bb'].round(4))
print("\n=== 6. 시간 동태: clergy 효과 연도별 ===")
for y0,y1 in [(2008,2011),(2012,2014),(2015,2016),(2017,2018)]:
    s=S[(S.year>=y0)&(S.year<=y1)]; mm=smf.logit("default ~ clergy + C(grade)+int+linc+dti+t60+lamt", data=s).fit(disp=0,maxiter=200)
    print(f"{y0}-{y1}: n_clergy {int(s.clergy.sum())} OR {np.exp(mm.params['clergy[T.True]']):.3f} p {mm.pvalues['clergy[T.True]']:.4f}")
